
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">



      <link href="/css/bootstrap.min.css" rel="stylesheet">
      <link href="/css/style.css" rel="stylesheet">
      <title>Boardroom booker</title>
  </head>

  <body>

  <div  id="content-container-admin">

      <div class="starter-template">

         <b style="background-color: #ffff00"><?=\Library\Session::getFlash()?></b>

          <?=$content ?>

      </div>

  </div>


  </body>
</html>


